version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz"
      - tar -xzf kustomize_v5.4.2_linux_amd64.tar.gz
      - mv kustomize /usr/local/bin/kustomize
      - kustomize version

  build:
    commands:
      - cd overlays/dev
      - kustomize build . > output.yaml
      - mkdir -p $CODEBUILD_SRC_DIR/artifacts
      - cp output.yaml $CODEBUILD_SRC_DIR/artifacts/

artifacts:
  files:
    - artifacts/output.yaml
  base-directory: $CODEBUILD_SRC_DIR