version: 0.2

phases:
  install:
    commands:
      - echo "Installing kustomize..."
      - curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz" || { echo "Failed to download kustomize"; exit 1; }
      - tar -xzf kustomize_v5.4.2_linux_amd64.tar.gz || { echo "Failed to extract kustomize"; exit 1; }
      - chmod +x kustomize
      - mv kustomize /usr/local/bin/kustomize || { echo "Failed to install kustomize"; exit 1; }
      - kustomize version || { echo "Kustomize verification failed"; exit 1; }

  build:
    commands:
      - echo "Building kustomize manifests..."
      - if [ ! -d "overlays/dev" ]; then echo "Error: overlays/dev directory not found"; exit 1; fi
      - cd overlays/dev && kustomize build . > output.yaml || { echo "Kustomize build failed"; exit 1; }
      - if [ ! -f "output.yaml" ]; then echo "Error: output.yaml not generated"; exit 1; fi
      - echo "Generated output.yaml contents:"
      - cat output.yaml
      - echo "Directory contents:"
      - ls -la
      - cd ../..

artifacts:
  files:
    - overlays/dev/output.yaml
  discard-paths: no