version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz"
      - tar -xzf kustomize_v5.4.2_linux_amd64.tar.gz
      - chmod +x kustomize
      - mv kustomize /usr/local/bin/
      - kustomize version

  build:
    commands:
      - mkdir -p overlays/dev
      - cd overlays/dev
      - kustomize build . > output.yaml
      - ls -la
      - cd ../..
      - mkdir -p $(pwd)/overlays/dev
      - cp overlays/dev/output.yaml $(pwd)/overlays/dev/

artifacts:
  files:
    - overlays/dev/output.yaml
  discard-paths: no