version: 0.2

phases:
  install:
    commands:
      - curl -LO "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv5.4.2/kustomize_v5.4.2_linux_amd64.tar.gz"
      - tar -xzf kustomize_v5.4.2_linux_amd64.tar.gz
      - mv kustomize /usr/local/bin/kustomize
      - kustomize version

  build:
    commands:
      - cd overlays/dev
      - kustomize build . > output.yaml
      - cat output.yaml
      - ls -la
      - cd ../..
      - mkdir -p $CODEBUILD_SRC_DIR/artifacts
      - cp overlays/dev/output.yaml $CODEBUILD_SRC_DIR/artifacts/
      - ls -la $CODEBUILD_SRC_DIR/artifacts/

artifacts:
  files:
    - overlays/dev/output.yaml
  discard-paths: no