apiVersion: v1 # API version for the service object
kind: Service # Specifies that this is a Service
metadata:
  name: nginx-service # Name of the deployment to patch
spec:
  type: NodePort # Change the service type to NodePort
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      nodePort: 30080