resources:
  - deployment.yaml # List of resource files to include in this configuration
  - service.yaml    # List of resource files to include in this configuration
configMapGenerator:
- name: my-app-config # Name of the ConfigMap
  literals:
    - app_name=MyKustomizeApp     # Key-value pairs
    - log_level=debug
secretGenerator: 
- name: my-app-secret    # Name of the secret
  literals: 
    - username=admin  # Key-value pairs; consider external management for real secrets  
    - password=czNjcjN0 # base64 encoded password
  type: Opaque # Type of the secret